name: flint_ui
description: Dart-first web UI components and browser rendering for Flint fullstack apps.
version: 0.1.8
homepage: https://flintdart.dev
repository: https://github.com/flint-dart/flint-ui
issue_tracker: https://github.com/flint-dart/flint-ui/issues
license: MIT

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flint_client: ^0.0.3
  universal_web: ^1.1.1+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
